name:                morpheus-sample
version:             0.1.0.0
github:              "wataru86/morpheus-sample"
license:             BSD3
author:              "Wataru Yamada"
maintainer:          "wataru86haskell@gmail.com"
copyright:           "Copyright (c) 2021 Wataru Yamada"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wataru86/morpheus-sample#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - morpheus-graphql
  - text
  - wai
  - warp
  - http-types

library:
  source-dirs: src

executables:
  morpheus-sample-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - morpheus-sample

tests:
  morpheus-sample-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - morpheus-sample
